version: '3.7'

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: minecraft
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
    ports:
      - 4326:4326
      - 4327:4327

  minecraft:
    image: ghcr.io/hoellenwesen/docker-minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    environment:
    - JAVA_XMS=2048M
    - JAVA_XMX=2048M
    - MINECRAFT_VERSION=latest
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/root/minecraft

volumes:
  minecraft:
